import { useState } from 'react';

export default function LandingPage({ onEnter }) {
    const [isHovered, setIsHovered] = useState(false);

    return (
        <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 50,
            fontFamily: '"Space Grotesk", sans-serif',
            background: 'radial-gradient(ellipse at center, #0f0728 0%, #030014 70%)'
        }}>
            {/* Background glow */}
            <div style={{
                position: 'absolute',
                width: '600px',
                height: '600px',
                borderRadius: '50%',
                background: 'radial-gradient(circle, rgba(124, 58, 237, 0.15) 0%, transparent 70%)',
                filter: 'blur(60px)',
                pointerEvents: 'none'
            }} />

            {/* Logo */}
            <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '16px',
                marginBottom: '48px'
            }}>
                <div style={{
                    width: '48px',
                    height: '48px',
                    borderRadius: '50%',
                    background: 'linear-gradient(135deg, #00d4ff 0%, #7c3aed 100%)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                }}>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2">
                        <polygon points="12 2 2 7 12 12 22 7 12 2" />
                        <polyline points="2 17 12 22 22 17" />
                        <polyline points="2 12 12 17 22 12" />
                    </svg>
                </div>
                <span style={{
                    color: '#e8e6f0',
                    fontSize: '24px',
                    fontWeight: '500',
                    letterSpacing: '2px'
                }}>
                    ADFORGE
                </span>
            </div>

            {/* Tagline */}
            <h1 style={{
                color: '#e8e6f0',
                fontSize: 'clamp(32px, 6vw, 56px)',
                fontWeight: '300',
                margin: '0 0 16px 0',
                letterSpacing: '-1px',
                textAlign: 'center',
                maxWidth: '700px',
                padding: '0 24px',
                lineHeight: 1.2
            }}>
                AI-Powered Ad Generation
            </h1>

            <p style={{
                color: '#6b6880',
                fontSize: '16px',
                margin: '0 0 48px 0',
                textAlign: 'center',
                maxWidth: '500px',
                padding: '0 24px',
                lineHeight: 1.6
            }}>
                Transform your ideas into stunning ad campaigns with images, audio, and video - all generated by AI.
            </p>

            {/* CTA Button */}
            <button
                onClick={onEnter}
                onMouseEnter={() => setIsHovered(true)}
                onMouseLeave={() => setIsHovered(false)}
                style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    padding: '16px 32px',
                    background: isHovered 
                        ? 'linear-gradient(135deg, #00d4ff 0%, #7c3aed 100%)' 
                        : 'rgba(124, 58, 237, 0.15)',
                    border: '1px solid rgba(124, 58, 237, 0.5)',
                    borderRadius: '12px',
                    color: isHovered ? '#fff' : '#e8e6f0',
                    fontSize: '15px',
                    fontWeight: '500',
                    cursor: 'pointer',
                    fontFamily: '"Space Grotesk", sans-serif',
                    transition: 'all 0.3s ease',
                    transform: isHovered ? 'scale(1.02)' : 'scale(1)'
                }}
            >
                Start Creating
                <svg 
                    width="20" 
                    height="20" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    strokeWidth="2"
                    style={{
                        transform: isHovered ? 'translateX(4px)' : 'translateX(0)',
                        transition: 'transform 0.3s ease'
                    }}
                >
                    <line x1="5" y1="12" x2="19" y2="12" />
                    <polyline points="12 5 19 12 12 19" />
                </svg>
            </button>

            {/* Features */}
            <div style={{
                display: 'flex',
                gap: '32px',
                marginTop: '64px',
                flexWrap: 'wrap',
                justifyContent: 'center',
                padding: '0 24px'
            }}>
                {[
                    { icon: 'M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z', label: 'Images' },
                    { icon: 'M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2z', label: 'Audio' },
                    { icon: 'M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z', label: 'Video' }
                ].map((item, i) => (
                    <div key={i} style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                        color: '#6b6880'
                    }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                            <path d={item.icon} />
                        </svg>
                        <span style={{ fontSize: '13px', letterSpacing: '1px' }}>{item.label}</span>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div style={{
                position: 'absolute',
                bottom: '24px',
                color: '#4a4660',
                fontSize: '12px',
                letterSpacing: '1px'
            }}>
                Powered by AI
            </div>
        </div>
    );
}
